;Sonic 2 Equate File
;hard mode and easy mode levels are the same size

;Bank 04

#define Art_Sonic					$D09466
#define Art_ALZ_Bubble					$D0CC66
#define Art_Badnik_Pig					$D0CD96
#define Art_Unused_Numbers				$D0D096
#define Art_SHZ_Leaves					$D0D116
#define Art_Badnik_Turtle				$D0D1BE

;Bank 05

#define Art_Sonic_Gliding				$D09466
#define Art_Sonic_Minecart				$D0B266

;Bank 06

#define Art_Sonic_Loop					$D09466
#define Art_CEZ_Wheel					$D0D066
#define Art_CEZ_Block					$D0D2C6

;Bank 07

#define Art_Icons_Numbers				$D09466
#define Art_Monitors_Generic				$D098C8
#define Art_Monitors					$D09A6E
#define Art_Monitor_0					$D09A6E
#define Art_Monitor_1					$D09B2E
#define Art_Monitor_2					$D09BEE
#define Art_Monitor_3					$D09CAE
#define Art_Monitor_4					$D09D6E
#define Art_Monitor_5					$D09E2E
#define Art_Monitor_6					$D09EEE
#define Art_Monitor_7					$D09FAE
#define Art_Monitor_8					$D0A06E
#define Art_Rings					$D0A12E
#define Art_GHZ_Moving_Platform				$D0A2FE
#define Art_SHZ_Glider					$D0A3F8
#define Art_Prison_Capsule				$D0A674
#define Art_Animals					$D0AF34
#define Art_Scrolling_Text_Background			$D0B534
#define Art_Signpost					$D0B588
#define Art_Minecart					$D0C208
#define Art_SilverSonic					$D0C54C
#define Art_SHZ_Log					$D0CDCC
#define Art_SHZ_Moving_Platform				$D0CE16

;Bank 08

#define Art_Intro_Sequence				$D09466
#define Art_Beta_Title					$D09B06
#define Mappings32_Intro				$D0A816
#define Mappings32_Title				$D0AB46
#define Layout_Intro					$D0AE98
#define Layout_Title					$D0AF18
#define Art_Mini_Sonic					$D0AF98		
#define Art_Intro_Scenery				$D0BC98
#define Art_Title_Sonic_Hand				$D0BE08
#define Art_Title_Tails_Face				$D0C098
#define Mappings_Title					$D0C208
#define DemoControlSequence_ALZ				$D0C4D8

;Bank 09

#define Palette_Update					$D09466
#define Palette_UpdateColours				$D094A4
#define Palette_Reset					$D094B3
#define Palette_FadeToColour				$D094C5
#define Palette_FadeToBlack				$D0952A
#define Palette_CalculateOffset				$D09583
#define Palette_811F					$D09593
#define Palette_812F					$D095A3
#define Palette_813F					$D095B3
#define Palette_TitleCards				$D095C3
#define Palette_GHZ_Sonic				$D095D3
#define Palette_SHZ1_3_Sonic				$D095E3
#define Palette_SHZ2_Sonic				$D095F3
#define Palette_ALZ1_3_Sonic				$D09603
#define Palette_ALZ2_Sonic				$D09613
#define Palette_UGZ_Sonic				$D09623
#define Palette_GMZ_Sonic				$D09633
#define Palette_SEZ_Sonic				$D09643
#define Palette_CEZ1_2_Sonic				$D09653
#define Palette_CEZ3_Sonic				$D09663
#define Palette_UGZ					$D09673
#define Palette_SHZ1_3					$D09683
#define Palette_SHZ2					$D09693
#define Palette_ALZ1_3					$D096A3
#define Palette_ALZ2					$D096B3
#define Palette_GHZ					$D096C3
#define Palette_GMZ					$D096D3
#define Palette_SEZ					$D096E3
#define Palette_CEZ1_2					$D096F3
#define Palette_CEZ3					$D09703
#define Palette_Intro					$D09713
#define Palette_Title					$D09723
#define Palette_Intro2					$D09733
#define Palette_Title2					$D09743
#define Palette_82DF					$D09753
#define Palette_Titlecard_UGZ				$D09763
#define Palette_Titlecard_SHZ				$D09773
#define Palette_Titlecard_ALZ				$D09783
#define Palette_Titlecard_GHZ				$D09793
#define Palette_Titlecard_GMZ				$D097A3
#define Palette_Titlecard_SEZ				$D097B3
#define Palette_Titlecard_CEZ				$D097C3
#define Palette_853F					$D097D3
#define Palette_Ending_Sonic				$D097E3
#define Palette_837F					$D097F3
#define Palette_Ending_Sequence				$D09803
#define LoopMotionData					$D09883
#define Art_LevelSelect_Font				$D0A193
#define Art_TitleCard_Text_Tiles			$D0A593
#define Art_TitleCard_Unknown				$D0B433
#define Art_TitleCard_Unknown2				$D0B4C9
#define Art_UGZ_Level_Tiles				$D0B518
#define Art_SHZ_Yellow_Bird				$D0C551
#define Art_ALZ_Spike					$D0C5D1
#define Art_GMZ_Moving_Platform				$D0C6C3
#define Art_SEZ_Moving_Platform				$D0C753
#define Art_Badnik_Newtron				$D0C85D
#define Art_Badnik_Bomb					$D0CBDD
#define Art_UGZ_Unknown					$D0CD0B
#define Art_Badnik_Crab					$D0CDF9
#define Art_ALZ_Unknown					$D0D119
#define Art_ALZ_Unknown2				$D0D169
#define Art_UGZ_Spikes					$D0D199
#define Art_GMZ_Spikes					$D0D239
#define Art_ALZ_Big_Bubble				$D0D2D9

;Bank 10

#define Art_SHZ_Level_Tiles				$D09466
#define Art_GHZ_Level_Tiles				$D0A642
#define Art_GMZ_Level_Tiles				$D0B712
#define Art_Ending_Text					$D0C748

;Bank 11

#define Mappings32_SHZ1_3				$D09466
#define Mappings32_SHZ2					$D0AE26
#define Layout_CEZ1					$D0C6E6

;Bank 12

#define Mappings32_GHZ					$D09466
#define Mappings32_ALZ					$D0AC26
#define Layout_SHZ3					$D0C5E6
#define Layout_GMZ3					$D0CD2C

;Bank 13

#define Layout_GHZ1					$D09466
#define Layout_GHZ2					$D0A0D2
#define Layout_GHZ3					$D0ACEB
#define Layout_SHZ1					$D0B7F8
#define Layout_SHZ2					$D0C4A8

;Bank 14

#define Layout_ALZ1					$D09466
#define Layout_ALZ2					$D0A3CF
#define Layout_ALZ3					$D0B266
#define Layout_UGZ1					$D0C098

;Bank 15

#define Mappings32_ALZ2					$D09466
#define Mappings32_UGZ					$D0B2E6
#define GameOverScreen_Data_GameOverTiles		$D0C9E6
#define ContinueScreen_Data_ContinueTiles		$D0CBD6
#define ContinueScreen_Data_NumberTiles			$D0CDC0
#define GameOverScreen_Data_TextMappings		$D0D1E4
#define ContinueScreen_Data_TextMappings		$D0D22C
#define ContinueScreen_Data_NumberMappings		$D0D274

;Bank 16

#define Art_Sonic_Mirrored				$D09466
#define Art_WavyLines					$D0CAE6
#define Art_UGZ_Fireball				$D0CB26
#define Art_Badnik_Lobster				$D0CBA6
#define Art_Badnik_Burrobot				$D0CE06
#define Art_Badnik_Motobug				$D0D0E8
#define Art_Badnik_Fish					$D0D28E

;Bank 17

#define Art_Sonic_Gliding_Mirrored			$D09466
#define Art_Sonic_Minecart_Mirrored			$D0B266

;Bank 18

#define Art_Sonic_Loop_Mirrored				$D09466
#define Art_SEZ_Block					$D0D066
#define Art_CEZ_Moving_Platform				$D0D0E6
#define Art_CEZ_Rock					$D0D1AC

;Bank 19

#define Layout_GMZ1					$D09466
#define Layout_GMZ2					$D0A0CF
#define Layout_SEZ1					$D0AEF8
#define Layout_SEZ2					$D0BE30
#define Art_Intro_Tails					$D0CBD4
#define Art_Intro_Tails_Eggman				$D0CE60

;Bank 20

#define Art_SEZ_Level_Tiles				$D09466
#define Art_SEZ2_Level_Tiles				$D0A490
#define Art_Boss_UGZ					$D0B568
#define Art_End						$D0C2A8
#define Art_Tails_Running				$D0C468
#define Art_Tails_Skid					$D0CEE8
#define Art_Tails_LookingUp				$D0D0A8
#define Art_ChaosEmerald_Grey				$D0D268
#define Art_ChaosEmerald_Blue				$D0D2E8
#define Art_ChaosEmerald_Green				$D0D368
#define Art_ChaosEmerald_Pink				$D0D3E8
#define Art_ChaosEmerald_Red				$D0D468
#define Art_ChaosEmerald_Yellow				$D0D4E8

;Bank 21

#define Art_ALZ_Level_Tiles				$D09466
#define Art_ALZ2_Level_Tiles				$D0A556
#define Art_CEZ_Level_Tiles				$D0B57C
#define Art_CEZ3_Level_Tiles				$D0C2E4

;Bank 22

#define Mappings32_GMZ					$D09466
#define Mappings32_SEZ1_3				$D0AEC6
#define Mappings32_Ending				$D0C586

;Bank 23

#define Mappings32_SEZ2					$D09466
#define Mappings32_CEZ3					$D0ACC6
#define Art_SHZ2_Level_Tiles				$D0B666
#define Layout_UGZ2					$D0C782

;Bank 24

#define Mappings32_CEZ1_2				$D09466
#define Art_Title_Screen				$D0AB66
#define Art_CEZ_Boss					$D0BF00
#define Art_CEZ3_Cloud					$D0C902

;Bank 25

#define UGZ_Title_Pic_Art				$D09466
#define SHZ_Title_Pic_Art				$D09E06
#define ALZ_Title_Pic_Art				$D0A876
#define GHZ_Title_Pic_Art				$D0B226
#define GMZ_Title_Pic_Art				$D0B8AC
#define SEZ_Title_Pic_Art				$D0C08C
#define CEZ_Title_Pic_Art				$D0C50C

#define UGZ_Title_Pic_Mappings				$D0CC6C
#define SHZ_Title_Pic_Mappings				$D0CD6C
#define ALZ_Title_Pic_Mappings				$D0CE6C
#define GHZ_Title_Pic_Mappings				$D0CF6C
#define GMZ_Title_Pic_Mappings				$D0D06C
#define SEZ_Title_Pic_Mappings				$D0D16C
#define CEZ_Title_Pic_Mappings				$D0D26C

;Bank 26

#define Art_GMZ_Boss					$D09466
#define Art_SHZ_Boss					$D09DA6
#define Art_ALZ_Boss					$D0AB66
#define Art_GHZ_Boss					$D0B4E6
#define Art_SHZ_Rock					$D0C7A6
#define Art_Block_Fragment				$D0C8C6
#define Art_Tails					$D0C8F0

;Bank 27

#define Layout_UGZ3					$D09466
#define Layout_SEZ3					$D09AEA
#define Layout_CEZ2					$D0A56A
#define Layout_CEZ3					$D0B1F6
#define Layout_Good_Ending				$D0B34C
#define Layout_Bad_Ending				$D0B4C6
#define Art_Ending_Tiles				$D0B637

;Bank 28

#include "appvars/bank28_equates.inc"

;Bank 29

#define DemoControlSequence_GHZ				$D09468
#define DemoControlSequence_SHZ				$D0A466
#define Art_Rings_UGZ					$D0B066
#define Art_Rings_SHZ1_3				$D0B366
#define Art_Rings_SHZ2					$D0B666
#define Art_Rings_ALZ					$D0B966
#define Art_Rings_GHZ					$D0BC66
#define Art_Rings_GMZ					$D0BF66
#define Art_Rings_SEZ					$D0C266
#define Art_Rings_CEZ					$D0C566
#define LABEL_B29_B400					$D0C866
#define LABEL_B29_B40C					$D0C873
#define LABEL_B29_B422					$D0C88D
#define LABEL_B29_B433					$D0C8A0
#define LABEL_B29_B4A9					$D0C91F
#define LABEL_B29_B4AF					$D0C926
#define LABEL_B29_B4F5					$D0C972
#define LABEL_B29_B510					$D0C98E
#define LABEL_B29_B51C					$D0C99C
#define DATA_B29_B522					$D0C9A3
#define DATA_B29_B542					$D0C9C3
#define EndSequence_Data_CreditsText			$D0C9D3

;Bank 30

#include "appvars/bank30_equates.inc"

;Bank 31

#include "appvars/bank31_equates.inc"