spasm64 -E appvars/ALZ.asm appvars/ALZ.8xv
spasm64 -E appvars/CEZ.asm appvars/CEZ.8xv
spasm64 -E appvars/GHZ.asm appvars/GHZ.8xv
spasm64 -E appvars/GMZ.asm appvars/GMZ.8xv
spasm64 -E appvars/SEZ.asm appvars/SEZ.8xv
spasm64 -E appvars/SHZ.asm appvars/SHZ.8xv
spasm64 -E appvars/UGZ.asm appvars/UGZ.8xv
spasm64 -E appvars/END.asm appvars/END.8xv
spasm64 -E appvars/MISC.asm appvars/MISC.8xv
spasm64 -E appvars/MAIN.asm appvars/MAIN.8xv
spasm64 -E appvars/INTRO.asm appvars/INTRO.8xv