spasm64 -E levels/ALZ.asm levels/ALZ.8xv
spasm64 -E levels/CEZ.asm levels/CEZ.8xv
spasm64 -E levels/CEZ3.asm levels/CEZ3.8xv
spasm64 -E levels/GHZ.asm levels/GHZ.8xv
spasm64 -E levels/GMZ.asm levels/GMZ.8xv
spasm64 -E levels/SEZ.asm levels/SEZ.8xv
spasm64 -E levels/SHZ.asm levels/SHZ.8xv
spasm64 -E levels/UGZ.asm levels/UGZ.8xv
spasm64 -E levels/ENDING.asm levels/ENDING.asm