.ASSUME ADL=0
;each line must be padded to 16 bytes
.db "CAST    SONIC   "
.db "                "
.db "COMPOSE TOMOZOU "
.db "COMPOSE SIMACHAN"
.db "COMPOSE RAY     "
.db "PROGRAM KO,KO   "
.db "PROGRAM SEMIMARU"
.db "PROGRAM TEA TEA "
.db "PROGRAM TOSIYAN "
.db "DISASM  GLITCH  "
.db "CE PORT GRUBBY  "
.db "ART     JLY KING"
.db "ART     NOBURIN "
.db "ART     TEZ     "
.db "ART     U,D,K   "
.db "EDIT    RAIZOU  "
.db "EDIT    M,SHIMA "
.db "EDIT    END     "
.db "EDIT    MARIYURI"
.db "SOUND   GATAO   "
.db "SOUND   NAO CHAN"
.db "SOUND   DAWASA  "
.db "THANKS  ASOHY   "
.db "THANKS  TAKU,S  "
.db "THANKS  THE HASE"
.db "THANKS  THOMAS Y"
.db "THANKS  OKUSAN  "
.db "THANKS  LUNARIAN"
.db "THANKS  HITMEN  "
.db "THANKS  DONALD C"
.db "THANKS  ASPECT  "
.db "THANKS  CEMETECH"
.db "THANKS  CE-PROG,"
.db "THANKS  S,RETRO "
.db "THANKS  ROCCOLOX"
.db "THANKS  TINY-H, "
.db "THANKS  OMNIMAGA"
.db "THANKS  MATEO   "
.db "THANKS  PIXELCAT"
.db "        ,AND YOU"
.db $FF